version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: medassist_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medassist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: medassist_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/medassist
      MONGO_URL: mongodb+srv://Jayanitha_S:<jayan@mo>@cluster0.v9ibxko.mongodb.net/?appName=Cluster0
      MONGO_DB_NAME: medassist
      JWT_SECRET: medassist_super_secret_jwt_key_milestone_1_dev
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: medassist_frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
