services:
  - type: web
    name: medassist-backend-api
    env: python
    region: singapore
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VALID_ADMIN_CODES
        value: ADMIN2026,ADMIN123,SUPERADMIN
      - key: VALID_CLINIC_CODES
        value: CLINIC2026,CLINIC123,MEDCLINIC
